[meta]
name     = "MLFeed: Race Data"
author   = "XertroV"
category = "MLHook"
version  = "0.5.12"

[script]
#__DEFINES__
dependencies = ["MLHook"]
exports = ["MLFeed_Export.as"]
shared_exports = ["MLFeed_ExportShared.as"]
module = "MLFeed"
# export_dependencies = ["MLHook"]
