[meta]
name     = "MLFeed: Race Data"
author   = "XertroV"
category = "MLHook"
version  = "0.3.6-pre"

[script]
#__DEFINES__
dependencies = ["MLHook"]
exports = ["Export.as"]
shared_exports = ["ExportShared.as"]
module = "MLFeed"
